version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306" 
